alter type public.task_status add value if not exists 'Awaiting Confirmation';
alter type public.task_status add value if not exists 'Under Review';
alter type public.task_status add value if not exists 'Cancelled';
alter type public.bid_status add value if not exists 'Cancelled';

alter table public.tasks
  add column if not exists completion_requested_at timestamptz,
  add column if not exists completion_confirmed_at timestamptz;

create table if not exists public.task_disputes (
  id bigint generated by default as identity primary key,
  task_id bigint not null references public.tasks(id) on delete cascade,
  opened_by bigint not null references public.user_profiles(id) on delete cascade,
  details text not null check (length(details) between 1 and 2000),
  status text not null default 'Open' check (status in ('Open','Resolved')),
  resolution text,
  resolved_by bigint references public.user_profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  resolved_at timestamptz
);
create index if not exists task_disputes_task_created_idx on public.task_disputes(task_id, created_at desc);
create unique index if not exists task_disputes_one_open_per_task_idx on public.task_disputes(task_id) where status = 'Open';
alter table public.task_disputes enable row level security;
revoke all on public.task_disputes from public, anon, authenticated;
grant all on public.task_disputes to service_role;
grant usage, select on sequence public.task_disputes_id_seq to service_role;

create table if not exists public.task_reviews (
  id bigint generated by default as identity primary key,
  task_id bigint not null references public.tasks(id) on delete cascade,
  reviewer_id bigint not null references public.user_profiles(id) on delete cascade,
  reviewee_id bigint not null references public.user_profiles(id) on delete cascade,
  rating smallint not null check (rating between 1 and 5),
  comment text not null default '' check (length(comment) <= 1000),
  created_at timestamptz not null default now(),
  unique(task_id, reviewer_id),
  check (reviewer_id <> reviewee_id)
);
create index if not exists task_reviews_reviewee_created_idx on public.task_reviews(reviewee_id, created_at desc);
alter table public.task_reviews enable row level security;
revoke all on public.task_reviews from public, anon, authenticated;
grant all on public.task_reviews to service_role;
grant usage, select on sequence public.task_reviews_id_seq to service_role;

create table if not exists public.task_notifications (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.user_profiles(id) on delete cascade,
  task_id bigint not null references public.tasks(id) on delete cascade,
  event_type text not null,
  dedupe_key text not null unique,
  title text not null,
  body text not null,
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);
create index if not exists task_notifications_user_unread_created_idx on public.task_notifications(user_id, is_read, created_at desc);
alter table public.task_notifications enable row level security;
revoke all on public.task_notifications from public, anon, authenticated;
grant all on public.task_notifications to service_role;
grant usage, select on sequence public.task_notifications_id_seq to service_role;

create or replace function public.accept_task_bid(p_task_id bigint, p_bid_id bigint)
returns table (bidder_id bigint, was_selected boolean)
language plpgsql security definer set search_path = '' as $$
declare
  current_status public.task_status;
  selected_bidder bigint;
begin
  select t.status into current_status from public.tasks t where t.id = p_task_id for update;
  if current_status is distinct from 'Open'::public.task_status then
    raise exception 'This task is no longer accepting bids.' using errcode = 'P0001';
  end if;
  select b.bidder_id into selected_bidder from public.bids b
    where b.id = p_bid_id and b.task_id = p_task_id and b.status = 'Pending'::public.bid_status for update;
  if selected_bidder is null then
    raise exception 'This bid is no longer available.' using errcode = 'P0001';
  end if;
  return query select b.bidder_id, false from public.bids b
    where b.task_id = p_task_id and b.status = 'Pending'::public.bid_status and b.id <> p_bid_id;
  update public.bids set status = 'Rejected'::public.bid_status
    where task_id = p_task_id and status = 'Pending'::public.bid_status and id <> p_bid_id;
  update public.bids set status = 'Accepted'::public.bid_status where id = p_bid_id;
  update public.tasks set status = 'In Progress'::public.task_status,
    completion_requested_at = null, completion_confirmed_at = null where id = p_task_id;
  return query select selected_bidder, true;
end;
$$;
revoke all on function public.accept_task_bid(bigint,bigint) from public, anon, authenticated;
grant execute on function public.accept_task_bid(bigint,bigint) to service_role;
