alter table public.tasks
  add column if not exists schedule_date date,
  add column if not exists task_mode text not null default 'on_site' check (task_mode in ('on_site', 'online', 'hybrid')),
  add column if not exists budget_type text not null default 'fixed' check (budget_type in ('fixed', 'negotiable')),
  add column if not exists materials_included boolean not null default false,
  add column if not exists requirements text not null default '',
  add column if not exists checklist jsonb not null default '[]'::jsonb;
create index if not exists tasks_owner_status_idx on public.tasks(user_id, status);

create table if not exists public.task_drafts (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.user_profiles(id) on delete cascade,
  data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists task_drafts_user_updated_idx on public.task_drafts(user_id, updated_at desc);
alter table public.task_drafts enable row level security;
revoke all on public.task_drafts from public, anon, authenticated;
grant all on public.task_drafts to service_role;
grant usage, select on sequence public.task_drafts_id_seq to service_role;
