-- TaskerPH data model for Supabase/PostgreSQL.
-- Authentication is managed by Supabase Auth. The integer profile IDs preserve
-- the existing frontend's ID expectations; auth_user_id binds each row to Auth.
create type public.app_role as enum ('superadmin', 'admin', 'user');
create type public.task_status as enum ('Open', 'In Progress', 'Completed');
create type public.bid_status as enum ('Pending', 'Accepted', 'Rejected');

create table public.user_profiles (
  id bigint generated by default as identity primary key,
  auth_user_id uuid not null unique references auth.users(id) on delete cascade,
  first_name varchar(80) not null,
  middle_initial varchar(5),
  last_name varchar(80) not null,
  email varchar(190) not null unique,
  role public.app_role not null default 'user',
  avatar_path text,
  created_at timestamptz not null default now()
);
create table public.tasks (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.user_profiles(id) on delete cascade,
  title varchar(180) not null,
  category varchar(80) not null,
  budget numeric(10,2) not null default 0 check (budget >= 0),
  location varchar(160) not null,
  description text not null,
  status public.task_status not null default 'Open',
  created_at timestamptz not null default now()
);
create index tasks_status_idx on public.tasks(status);
create index tasks_category_idx on public.tasks(category);
create table public.bids (
  id bigint generated by default as identity primary key,
  task_id bigint not null references public.tasks(id) on delete cascade,
  bidder_id bigint not null references public.user_profiles(id) on delete cascade,
  amount numeric(10,2) not null check (amount >= 0),
  message varchar(1000) not null,
  status public.bid_status not null default 'Pending',
  removal_reason varchar(1000),
  created_at timestamptz not null default now(),
  unique(task_id, bidder_id)
);
create index bids_status_idx on public.bids(status);
create table public.messages (
  id bigint generated by default as identity primary key,
  task_id bigint not null references public.tasks(id) on delete cascade,
  sender_id bigint not null references public.user_profiles(id) on delete cascade,
  recipient_id bigint not null references public.user_profiles(id) on delete cascade,
  body varchar(2000) not null,
  read_at timestamptz,
  created_at timestamptz not null default now()
);
create index messages_thread_idx on public.messages(task_id, sender_id, recipient_id, created_at);
create table public.notification_reads (
  user_id bigint not null references public.user_profiles(id) on delete cascade,
  notification_type text not null check (notification_type = 'bid'),
  reference_id bigint not null,
  read_at timestamptz not null default now(),
  primary key(user_id, notification_type, reference_id)
);
create table public.saved_tasks (
  user_id bigint not null references public.user_profiles(id) on delete cascade,
  task_id bigint not null references public.tasks(id) on delete cascade,
  saved_at timestamptz not null default now(),
  primary key(user_id, task_id)
);
create index saved_tasks_saved_at_idx on public.saved_tasks(user_id, saved_at);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('avatars', 'avatars', true, 3145728, array['image/jpeg','image/png','image/webp','image/gif'])
on conflict (id) do nothing;

-- Profile rows are created alongside Supabase Auth accounts. The client may only
-- create a regular user profile; elevated roles must be assigned by an admin.
create function public.create_profile_for_new_user()
returns trigger language plpgsql security definer set search_path = '' as $$
begin
  insert into public.user_profiles (auth_user_id, first_name, middle_initial, last_name, email)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'first_name', ''),
    nullif(new.raw_user_meta_data ->> 'middle_initial', ''),
    coalesce(new.raw_user_meta_data ->> 'last_name', ''),
    new.email
  );
  return new;
end;
$$;
create trigger on_auth_user_created after insert on auth.users
for each row execute procedure public.create_profile_for_new_user();

alter table public.user_profiles enable row level security;
alter table public.tasks enable row level security;
alter table public.bids enable row level security;
alter table public.messages enable row level security;
alter table public.notification_reads enable row level security;
alter table public.saved_tasks enable row level security;
create policy "Profiles are viewable by signed-in users" on public.user_profiles for select to authenticated using (true);
create policy "Open tasks are public" on public.tasks for select using (true);
create policy "Bids visible to task participants" on public.bids for select to authenticated using (
  exists(select 1 from public.user_profiles p where p.id = bidder_id and p.auth_user_id = auth.uid()) or exists(select 1 from public.tasks t join public.user_profiles p on p.id = t.user_id where t.id = task_id and p.auth_user_id = auth.uid())
);
create policy "Conversation participants read messages" on public.messages for select to authenticated using (exists(select 1 from public.user_profiles p where p.id=sender_id and p.auth_user_id=auth.uid()) or exists(select 1 from public.user_profiles p where p.id=recipient_id and p.auth_user_id=auth.uid()));
create policy "Public avatar reads" on storage.objects for select using (bucket_id = 'avatars');
create policy "Users upload own avatar" on storage.objects for insert to authenticated with check (bucket_id = 'avatars' and (storage.foldername(name))[1] = (select p.id::text from public.user_profiles p where p.auth_user_id = auth.uid()));
create policy "Users update own avatar" on storage.objects for update to authenticated using (bucket_id = 'avatars' and (storage.foldername(name))[1] = (select p.id::text from public.user_profiles p where p.auth_user_id = auth.uid()));
create policy "Users delete own avatar" on storage.objects for delete to authenticated using (bucket_id = 'avatars' and (storage.foldername(name))[1] = (select p.id::text from public.user_profiles p where p.auth_user_id = auth.uid()));
