create table if not exists public.task_reports (
  id bigint generated by default as identity primary key,
  task_id bigint not null references public.tasks(id) on delete cascade,
  reporter_id bigint not null references public.user_profiles(id) on delete cascade,
  reason varchar(80) not null,
  details varchar(1000) not null default '',
  status varchar(20) not null default 'Open' check (status in ('Open','Reviewed','Dismissed')),
  created_at timestamptz not null default now(),
  unique(task_id, reporter_id)
);
create index if not exists task_reports_created_idx on public.task_reports(created_at desc);
alter table public.task_reports enable row level security;
revoke all on public.task_reports from public, anon, authenticated;
grant all on public.task_reports to service_role;
grant usage, select on sequence public.task_reports_id_seq to service_role;

-- Dashboard event history is read and written only through the authenticated,
-- service-role API after it verifies the caller's role.
revoke all on public.account_activity from public, anon, authenticated;
grant all on public.account_activity to service_role;
grant usage, select on sequence public.account_activity_id_seq to service_role;
