alter type public.app_role add value if not exists 'moderator';
alter type public.app_role add value if not exists 'support';

alter table public.user_profiles
  add column if not exists is_suspended boolean not null default false,
  add column if not exists suspension_reason text,
  add column if not exists suspended_until timestamptz;

alter table public.task_reports
  add column if not exists resolution_note text,
  add column if not exists reviewed_by bigint,
  add column if not exists reviewed_at timestamptz;

create table if not exists public.admin_audit_events (
  id bigint generated by default as identity primary key,
  actor_id bigint,
  actor_name text not null,
  actor_email text not null,
  action varchar(80) not null,
  target_type varchar(40),
  target_id text,
  target_label text,
  reason text not null default '',
  before_state jsonb,
  after_state jsonb,
  created_at timestamptz not null default now()
);
create index if not exists admin_audit_events_created_idx
  on public.admin_audit_events(created_at desc, id desc);
create index if not exists admin_audit_events_actor_idx
  on public.admin_audit_events(actor_id, created_at desc);
alter table public.admin_audit_events enable row level security;
revoke all on public.admin_audit_events from public, anon, authenticated;
grant all on public.admin_audit_events to service_role;
grant usage, select on sequence public.admin_audit_events_id_seq to service_role;

create or replace function public.admin_dashboard_trends(p_days integer default 30, p_category text default null)
returns table (
  day date,
  registrations bigint,
  tasks bigint,
  completions bigint,
  reports bigint
)
language sql
security definer
set search_path = ''
as $$
  with days as (
    select generate_series(current_date - (greatest(7, least(p_days, 90)) - 1), current_date, interval '1 day')::date as day
  ),
  registrations as (
    select created_at::date as day, count(*) as count
    from public.user_profiles
    where created_at >= current_date - (greatest(7, least(p_days, 90)) - 1)
    group by created_at::date
  ),
  task_counts as (
    select created_at::date as day, count(*) as tasks
    from public.tasks
    where created_at >= current_date - (greatest(7, least(p_days, 90)) - 1)
      and (p_category is null or category = p_category)
    group by created_at::date
  ),
  completion_counts as (
    select completion_confirmed_at::date as day, count(*) as completions
    from public.tasks
    where completion_confirmed_at >= current_date - (greatest(7, least(p_days, 90)) - 1)
      and (p_category is null or category = p_category)
    group by completion_confirmed_at::date
  ),
  report_counts as (
    select created_at::date as day, count(*) as count
    from public.task_reports
    where created_at >= current_date - (greatest(7, least(p_days, 90)) - 1)
    group by created_at::date
  )
  select days.day,
    coalesce(registrations.count, 0),
    coalesce(task_counts.tasks, 0),
    coalesce(completion_counts.completions, 0),
    coalesce(report_counts.count, 0)
  from days
  left join registrations using (day)
  left join task_counts using (day)
  left join completion_counts using (day)
  left join report_counts using (day)
  order by days.day;
$$;
revoke all on function public.admin_dashboard_trends(integer, text) from public, anon, authenticated;
grant execute on function public.admin_dashboard_trends(integer, text) to service_role;

create or replace function public.admin_dashboard_metrics()
returns table (account_count bigint, admin_count bigint, active_count bigint)
language sql
security definer
set search_path = ''
as $$
  select
    (select count(*) from public.user_profiles where role <> 'superadmin'),
    (select count(*) from public.user_profiles where role::text in ('admin','moderator','support')),
    (select count(*) from public.account_presence where last_seen_at >= now() - interval '5 minutes');
$$;
revoke all on function public.admin_dashboard_metrics() from public, anon, authenticated;
grant execute on function public.admin_dashboard_metrics() to service_role;
