-- Private account presence and audit history, readable only through the
-- service-role-backed API after it verifies the caller is a superadmin.
create table if not exists public.account_presence (
  user_id bigint primary key references public.user_profiles(id) on delete cascade,
  last_login_at timestamptz,
  last_seen_at timestamptz
);

create table if not exists public.account_activity (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.user_profiles(id) on delete cascade,
  event_type varchar(80) not null,
  summary varchar(180) not null,
  reference_type varchar(40),
  reference_id text,
  created_at timestamptz not null default now()
);

create index if not exists account_activity_created_idx
  on public.account_activity(created_at desc);
create index if not exists account_activity_user_created_idx
  on public.account_activity(user_id, created_at desc);

alter table public.account_presence enable row level security;
alter table public.account_activity enable row level security;
revoke all on public.account_presence, public.account_activity from public, anon, authenticated;
grant all on public.account_presence, public.account_activity to service_role;
grant usage, select on sequence public.account_activity_id_seq to service_role;

create or replace function public.touch_account_presence(p_user_id bigint, p_is_login boolean default false)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.account_presence (user_id, last_login_at, last_seen_at)
  values (p_user_id, case when p_is_login then now() else null end, now())
  on conflict (user_id) do update
    set last_login_at = case when p_is_login then now() else public.account_presence.last_login_at end,
        last_seen_at = case
          when p_is_login or public.account_presence.last_seen_at < now() - interval '1 minute' then now()
          else public.account_presence.last_seen_at
        end
    where p_is_login or public.account_presence.last_seen_at < now() - interval '1 minute';
end;
$$;

revoke all on function public.touch_account_presence(bigint, boolean) from public, anon, authenticated;
grant execute on function public.touch_account_presence(bigint, boolean) to service_role;
