create table if not exists public.staff_permissions (
  user_id bigint primary key references public.user_profiles(id) on delete cascade,
  can_view_users boolean not null default false,
  can_moderate_tasks boolean not null default false,
  can_review_reports boolean not null default false,
  can_resolve_disputes boolean not null default false,
  updated_by bigint references public.user_profiles(id) on delete set null,
  updated_at timestamptz not null default now()
);
alter table public.staff_permissions enable row level security;
revoke all on public.staff_permissions from public, anon, authenticated;
grant all on public.staff_permissions to service_role;

create table if not exists public.suspension_appeals (
  id bigint generated by default as identity primary key,
  user_id bigint references public.user_profiles(id) on delete set null,
  claimant_email text not null,
  claimant_name text not null,
  reason text not null check (length(reason) between 20 and 2000),
  status varchar(20) not null default 'Open' check (status in ('Open','Approved','Denied')),
  resolution_note text,
  reviewed_by bigint references public.user_profiles(id) on delete set null,
  reviewed_at timestamptz,
  created_at timestamptz not null default now()
);
create unique index if not exists suspension_appeals_one_open_per_user_idx
  on public.suspension_appeals(user_id) where status = 'Open' and user_id is not null;
create index if not exists suspension_appeals_created_idx
  on public.suspension_appeals(created_at desc, id desc);
alter table public.suspension_appeals enable row level security;
revoke all on public.suspension_appeals from public, anon, authenticated;
grant all on public.suspension_appeals to service_role;
grant usage, select on sequence public.suspension_appeals_id_seq to service_role;

create table if not exists public.platform_announcements (
  id bigint generated by default as identity primary key,
  created_by bigint references public.user_profiles(id) on delete set null,
  title varchar(120) not null,
  body varchar(2000) not null,
  audience varchar(20) not null default 'everyone' check (audience in ('everyone','members','staff')),
  starts_at timestamptz not null default now(),
  expires_at timestamptz,
  is_published boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (expires_at is null or expires_at > starts_at)
);
create index if not exists platform_announcements_active_idx
  on public.platform_announcements(is_published, starts_at desc, expires_at);
alter table public.platform_announcements enable row level security;
revoke all on public.platform_announcements from public, anon, authenticated;
grant all on public.platform_announcements to service_role;
grant usage, select on sequence public.platform_announcements_id_seq to service_role;

create table if not exists public.announcement_reads (
  announcement_id bigint not null references public.platform_announcements(id) on delete cascade,
  user_id bigint not null references public.user_profiles(id) on delete cascade,
  read_at timestamptz not null default now(),
  primary key (announcement_id,user_id)
);
alter table public.announcement_reads enable row level security;
revoke all on public.announcement_reads from public, anon, authenticated;
grant all on public.announcement_reads to service_role;

create or replace function public.admin_analytics_summary(p_days integer default 30)
returns table (
  registrations bigint,
  active_users bigint,
  tasks_created bigint,
  tasks_completed bigint,
  tasks_cancelled bigint,
  disputes_opened bigint,
  reports_opened bigint,
  avg_report_response_hours numeric,
  completion_rate numeric,
  cancellation_rate numeric,
  dispute_rate numeric
)
language sql
security definer
set search_path = ''
as $$
  with period as (
    select now() - make_interval(days => greatest(7, least(p_days, 90))) as since_at
  ),
  task_totals as (
    select
      count(*) filter (where t.created_at >= period.since_at) as created,
      count(*) filter (where t.completion_confirmed_at >= period.since_at) as completed,
      count(*) filter (where t.status = 'Cancelled' and t.created_at >= period.since_at) as cancelled
    from public.tasks t cross join period
  ),
  activity_totals as (
    select
      (select count(*) from public.user_profiles p, period where p.created_at >= period.since_at) as registrations,
      (select count(*) from public.account_presence ap where ap.last_seen_at >= now() - interval '5 minutes') as active_users,
      (select count(*) from public.task_disputes d, period where d.created_at >= period.since_at) as disputes,
      (select count(*) from public.task_reports r, period where r.created_at >= period.since_at) as reports,
      (select avg(extract(epoch from (r.reviewed_at-r.created_at))/3600)
        from public.task_reports r, period
        where r.created_at >= period.since_at and r.reviewed_at is not null) as response_hours
  )
  select
    activity_totals.registrations,
    activity_totals.active_users,
    task_totals.created,
    task_totals.completed,
    task_totals.cancelled,
    activity_totals.disputes,
    activity_totals.reports,
    round(activity_totals.response_hours::numeric, 1),
    case when task_totals.created=0 then 0 else round(task_totals.completed::numeric*100/task_totals.created,1) end,
    case when task_totals.created=0 then 0 else round(task_totals.cancelled::numeric*100/task_totals.created,1) end,
    case when task_totals.created=0 then 0 else round(activity_totals.disputes::numeric*100/task_totals.created,1) end
  from task_totals cross join activity_totals;
$$;
revoke all on function public.admin_analytics_summary(integer) from public, anon, authenticated;
grant execute on function public.admin_analytics_summary(integer) to service_role;

create or replace function public.admin_analytics_categories(p_days integer default 30)
returns table (category text, tasks bigint, completed bigint, cancelled bigint)
language sql
security definer
set search_path = ''
as $$
  select t.category, count(*),
    count(*) filter (where t.completion_confirmed_at is not null),
    count(*) filter (where t.status = 'Cancelled')
  from public.tasks t
  where t.created_at >= now() - make_interval(days => greatest(7, least(p_days, 90)))
  group by t.category
  order by count(*) desc, t.category
  limit 12;
$$;
revoke all on function public.admin_analytics_categories(integer) from public, anon, authenticated;
grant execute on function public.admin_analytics_categories(integer) to service_role;
